### ISSUE TITLE
Add in password confirm functionality

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_policy#2]
Password confirm had to be stripped out of the user form because it was causing major conflicts when I attempted to validate the password against the applied policies.

**Comment by nerdstein** [comment]
@nagwani ping ping for visibility

**Comment by nerdstein** [comment]
https://github.com/d8-contrib-modules/password_policy/blob/master/password_policy.module#L30-L31

**Comment by mjl3475** [comment]
Closing per @nagwani
