### ISSUE TITLE
Constraints disappear in add new user.

### ISSUE THREAD

**Issue by mjl3475** [d8-contrib-modules/password_policy#28]
Replication:
1. Create a password policy with a length constraint, apply to Authed users.
2. Navigate to /admin/people/create
3. Note constraints exist
4. Type in failing password
5. Constraints disappear and only read "There are no constraints for the selected user roles"

**Comment by nerdstein** [comment]
Assigning to me to investigate

**Comment by nerdstein** [comment]
on beta14....

Able to reproduce

**Comment by nerdstein** [comment]
No JS errors, going to backend...

**Comment by nerdstein** [comment]
Awaiting merge of #38

**Comment by nerdstein** [comment]
Merged, closing
