### ISSUE TITLE
Replace TravisCI with Drupal-ti

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_policy#40]
Need this issue to be resolved:

https://github.com/LionsAd/drupal_ti/issues/39

Then, drop in custom logic for downloading ctools dependency between site install and module install

**Comment by nerdstein** [comment]
@damontgomery can you work on this?

**Comment by damontgomery** [comment]
@nerdstein, Yes, I'll give it a shot!

**Comment by damontgomery** [comment]
#53
