### ISSUE TITLE
Cannot edit user form

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_policy#42]
Uncaught PHP Exception Drupal\\Core\\Entity\\EntityStorageException: "Entity validation was skipped." at /var/www/drupal/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php line 755, referer: http://d8.dev/user/1/edit

Steps:
1. go to /user/1/edit
2. try to save form

**Comment by nerdstein** [comment]
@nagwani - did you see this during testing?

**Comment by nerdstein** [comment]
https://www.drupal.org/node/2453175

**Comment by mjl3475** [comment]
Probably this guy here: https://github.com/d8-contrib-modules/password_policy/blob/master/password_policy.module#L48-L49

**Comment by nerdstein** [comment]
Agreed. The first thing I would try is just $form['validate'] and $form['submit']

I was going to try it last night and felt like crap

**Comment by mjl3475** [comment]
I think the submit action is fine as is. Only the validate should need to change according to the patch from the d.o issue.

**Comment by mjl3475** [comment]
Fixed it. I'll submit the PR.

**Comment by nerdstein** [comment]
@nagwani ^^^^

**Comment by mjl3475** [comment]
https://github.com/d8-contrib-modules/password_policy/pull/43

**Comment by nerdstein** [comment]
Merged, closing
