### ISSUE TITLE
Enforce policy when user gains role

### ISSUE THREAD

**Issue by CashWilliams** [d8-contrib-modules/password_policy#50]
### Steps:

- Create a password policy and enable for 'Administrator' role
- Create a test user with no roles, which has password that fails the policy 'password'
- Edit the test user and add the 'Administrator' role

### Expected:

An error or message would be displayed when adding the role that states the user's password does not meet requirements.

Need to discuss options for what should happen. 

*Options:*

- Password is marked for force reset
- User is not saved with form error
- (other ideas?)

### Actual:

The user is saved and can login with the poor password into what should now be a policy enforced role.

**Comment by nerdstein** [comment]
Is this assumed to check the user's current password?

**Comment by nerdstein** [comment]
We can expire the user with the following conditions...
1. Added roles
2. No password update

**Comment by CashWilliams** [comment]
Seems to be an issue with D7 as well https://www.drupal.org/node/2451159

**Comment by nagwani** [comment]
Pull request sent https://github.com/d8-contrib-modules/password_policy/pull/57

**Comment by nagwani** [comment]
@nerdstein Can this be closed?
