### ISSUE TITLE
Add configuration dependencies to Password Policy config yml files

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_policy#54]
Password policy has configuration yml files under config/install. Currently they are not registered back to the password_policy module, and should be so the configuration is installed/uninstalled with the module.

Here are some examples from core that provide the functionality that Password Policy's configuration needs:

core/modules/user/config/optional/rdf.mapping.user.user.yml
dependencies:
-  module:
    - user

The example above demonstrates how configuration can set a dependency for the "user" module (install and uninstall will add/remove config respectively). In our case, we need our configuration to set the dependency of "password_policy" for all config files located under "config/install".

Currently, password_policy.install manually removes the field configuration defined in config/install. By enabling this dependency within Password Policy's "config/install", this means we can remove the code from the uninstall hook that manually removes some of the fields defined in configuration.

**Comment by msherron** [comment]
Completed in https://github.com/d8-contrib-modules/password_policy/pull/55
