### ISSUE TITLE
Error on User Register

### ISSUE THREAD

**Issue by nagwani** [d8-contrib-modules/password_policy#60]
Error on new user registration 

Drupal\Core\Entity\EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'field_password_expiration_value' at row 1: INSERT INTO {user__field_password_expiration} (entity_id, revision_id, bundle, delta, langcode, field_password_expiration_value) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5); Array ( [:db_insert_placeholder_0] => 2 [:db_insert_placeholder_1] => 2 [:db_insert_placeholder_2] => user [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => en [:db_insert_placeholder_5] => ) in Drupal\Core\Entity\Sql\SqlContentEntityStorage->save() (line 757 of /opt/devdesktop2/drupal/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).

**Comment by nerdstein** [comment]
Submitted in PR #63 to resolve issue
